apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: python:3
    args:
    - python
    - -c
    - >
      #!/usr/bin/python3
      from datetime import date
      today = date.today()
      fdate = date.today().strftime('%d/%m/%Y')
      i=0;
      while true;
      do
        print("Today's current date is -", today) >> /var/log/1.log
        print("Date in dd/mm/YYYY format -", fdate) >> /var/log/2.log
        i=$((i+1));
        sleep 1;
      done
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    emptyDir: {}
